### ISSUE TITLE
Error or warn: fail? best practice?

### ISSUE THREAD

**Issue by sveisvei** [finn-no/eslint-config-finn#56]
What  rules fail or error?
Should builds fail/stop on errors?
Should builds fail/stop on warnings?

**Comment by peternic** [comment]
Rules that does not break the build will only create noise. And I have never understood why have rules that does not make you do something. 
Imao 😈

**Comment by SimenB** [comment]
you have no choice WRT errors in eslint, they will fail.

Errors can get a max number.

We might want to set rules to warnings if it's too much work to fix them (such as `eqeqeq` in mfinn), and attach the max number that's the current number of warnings.

Other than that, I don't see the need for them.

**Comment by peternic** [comment]
I understand the hassle of fixing mfinn, but I don't think the max number will work as expected, 

Because not everybody will have good knowledge about the different rules, and if one gets 90 warnings when building, most certain everybody will be overwhelmed, and not able to see their own warnings. 
And then, they will rather raise the max-number than fix the warning.

Just as an example (I have not read the commit messages, so maybe there are a good reason), I got three random commits the last 4 months from mfinn.

From mars (**84** warnings allowed)
https://git.finn.no/projects/APPS/repos/mfinn/browse/package.json?until=e71f4b3c78fdeca5371cc2d2478c547288c09f2c

From april (**95** warnings allowed) 
https://git.finn.no/projects/APPS/repos/mfinn/browse/package.json?until=ad44fa90e9f457324c15ca2cae4b6e63d270b130)

From june (**110** warnings allowed)
https://git.finn.no/projects/APPS/repos/mfinn/browse/package.json?until=9a1b9732ed5991c45b35787dfa3758575d5768b6

What about rather disable eslint for the cases explicit in the code, then it is also documented which is to be ignored...?

**Comment by peternic** [comment]
In addition, if we add specific comments disabling eslint for difficult stuff to change instead of ignore warnings, hopefully when people read code for inspiration and see the comments, they will more likely understand that they should not copy the code direct 😃

**Comment by CMTegner** [comment]
I'm with @peternic on this one. What doesn't break the build will ultimately just get ignored, no matter how urgent you make it look.

**Comment by SimenB** [comment]
Is it better to disable a rule than make it warning? Ref `eqeqeq`

**Comment by peternic** [comment]
If a rule makes us write more functional and readable code, it seems strange to disable the rule for new code, just because it might be difficult to fix the rule on old code.

But I think this depends on the rule. Cosmetic rules, might be up for discussion, but rules that might prevent errors should be more important than old code.

For the specific `eqeqeq`, if I understand it correctly, that rule can actually catch errors in some cases.
